//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Goldfinch.Core.ContentTypes
{
	/// <summary>
	/// Represents a content item of type <see cref="SpeakingEngagement"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class SpeakingEngagement : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Goldfinch.SpeakingEngagement";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// Title.
		/// </summary>
		public string Title { get; set; }


		/// <summary>
		/// Description.
		/// </summary>
		public string Description { get; set; }


		/// <summary>
		/// EventName.
		/// </summary>
		public string EventName { get; set; }


		/// <summary>
		/// EventDate.
		/// </summary>
		public DateTime EventDate { get; set; }


		/// <summary>
		/// EventLocation.
		/// </summary>
		public string EventLocation { get; set; }


		/// <summary>
		/// RecordingLink.
		/// </summary>
		public string RecordingLink { get; set; }
	}
}