//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Goldfinch.Core.ContentTypes
{
	/// <summary>
	/// Defines a contract for content types with the <see cref="IBaseContentFields"/> reusable schema assigned.
	/// </summary>
	public interface IBaseContentFields
	{
		/// <summary>
		/// Code name of the reusable field schema.
		/// </summary>
		public const string REUSABLE_FIELD_SCHEMA_NAME = "BaseContentFields";


		/// <summary>
		/// BaseContentTitle.
		/// </summary>
		public string BaseContentTitle { get; set; }


		/// <summary>
		/// BaseContentShortDescription.
		/// </summary>
		public string BaseContentShortDescription { get; set; }
	}
}