//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace Goldfinch.Core.ContentTypes
{
	/// <summary>
	/// Represents a page of type <see cref="BlogListing"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class BlogListing : IWebPageFieldsSource, IBaseContentFields, ISeoFields
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Goldfinch.BlogListing";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// BaseContentTitle.
		/// </summary>
		public string BaseContentTitle { get; set; }


		/// <summary>
		/// BaseContentShortDescription.
		/// </summary>
		public string BaseContentShortDescription { get; set; }


		/// <summary>
		/// SeoTitle.
		/// </summary>
		public string SeoTitle { get; set; }


		/// <summary>
		/// SeoShortDescription.
		/// </summary>
		public string SeoShortDescription { get; set; }


		/// <summary>
		/// SeoCanonicalUrl.
		/// </summary>
		public string SeoCanonicalUrl { get; set; }
	}
}